### ISSUE TITLE
How can i load dynamic view with the source form database

### ISSUE THREAD

**Issue by ngohungphuc** [vsmoraes/pdf-laravel5#12]
I'm passing the $cv_info to view to show dynamic result.But it's said 

> Undefined variable: cv_info (View: D:\xampp\htdocs\FreelancerJob\resources\views\ui\UserInfo\viewCV.blade.php)

Here is my controller 

```
$cv_info=CV::where('id','=',$cv_id)->first();
        $html = view('ui.userinfo.viewCV',$cv_info)->render();

        return $this->pdf
        ->load($html)
        ->show();
```

How can i fix it.Thanks for your help

**Comment by vsmoraes** [comment]
Hello there!

The `view` function expects an array as the second parameter (see: https://github.com/laravel/framework/blob/5.2/src/Illuminate/Foundation/helpers.php#L729) and you're passing and `object` from Eloquent.

Try `$html = view('ui.userinfo.viewCV', [$cv_info])->render();`

PS: I'm closing this issue because.. well, it's not an issue.
